FROM python:3.6

ADD docker/requirements/requirements.txt .
RUN pip3 install -r requirements.txt && \
    rm requirements.txt

WORKDIR /src

COPY src/ /src

ENV PYTHONPATH $PYTHONPATH:/src

ADD docker/entrypoints/docker-entrypoint-worker.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
