FROM python:3.6

ADD docker/requirements/requirements.txt .
RUN pip3 install -r requirements.txt && \
    rm requirements.txt

ADD docker/entrypoints/docker-entrypoint-dashboard.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
